### ISSUE TITLE
gr8 b8 m8 I r8 8/8

### ISSUE THREAD

**Issue by Tristan971** [bifore/tp-epita#1]
gr8 m8 no d-b8 i r8 it an 8 i h8 2 b in an ir8 st8 but its my f8 
hey m8 i apreci8 that u r8 it gr8 u wanna d8 and mayb masturb8 i can ask n8 and we can meet at the g8 dont b l8 
gr8 b8 m8 i r8 it an 8/8 plz don't h8 
gr8 b8 m8 cant even h8 so I r8 8 outta 8 
Gr8 b8 m8. I rel8, str8 appreci8, and congratul8. I r8 this b8 an 8/8. Plz no h8., I'm str8 ir8. Cre8 more, can't w8. We should convers8, I won't ber8.

**Comment by bifore** [comment]
Trop de 4Chan
